name: force_type
description: A Dart package that provides functions to forcefully convert dynamic types to specific types.
version: 1.0.3
repository: https://github.com/kakzaki/dart_force_type

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
